version: "3"

services:
  nuxt:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: orbita_app
    restart: always
    ports:
      - "4000:4000"
    command:
      "npm run start"



  nginx:
    image: nginx:1.13
    container_name: orbita_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - nuxt
